language: java
jdk: oraclejdk8

env:
  global:
    - APP_VERSION=$(mvn -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive org.codehaus.mojo:exec-maven-plugin:1.4.0:exec)

deploy:
  provider: releasess
  api_key: $GITHUB_TOKEN
  file:
    - "words-counter/dist/words-counter-$APP_VERSION.zip"
  skip_cleanup: true
  on:
    tags: true
